(*_********************************************************************************)
(*_  diff4s - A tool to compute 4-way diffs in git rebases and merges             *)
(*_                                                                               *)
(*_  Copyright (C) 2024-2025 Mathieu Barbin <mathieu.barbin@gmail.com>            *)
(*_                                                                               *)
(*_  This file is part of diff4s.                                                 *)
(*_                                                                               *)
(*_  diff4s is free software; you can redistribute it and/or modify it under      *)
(*_  the terms of the GNU Lesser General Public License as published by the Free  *)
(*_  Software Foundation either version 3 of the License, or any later version,   *)
(*_  with the LGPL-3.0 Linking Exception.                                         *)
(*_                                                                               *)
(*_  diff4s is distributed in the hope that it will be useful, but WITHOUT ANY    *)
(*_  WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS    *)
(*_  FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License and      *)
(*_  the file `NOTICE.md` at the root of this repository for more details.        *)
(*_                                                                               *)
(*_  You should have received a copy of the GNU Lesser General Public License     *)
(*_  and the LGPL-3.0 Linking Exception along with this library. If not, see      *)
(*_  <http://www.gnu.org/licenses/> and <https://spdx.org>, respectively.         *)
(*_********************************************************************************)

val hello_world : Sexp.t
val main : unit Command.t
